### ISSUE TITLE
Adapt your module to use it on nodemcu firmware - esp32 boards

### ISSUE THREAD

**Issue by ezbella** [kedorlaomer/lua-cron#1]
Hi! First of all, thanks a lot for sharing your cron code! It was a lifesaver when I found out that nodemcu esp32 did not support cron module. So I reused your code, made some adjustments for the sake of simplification, added some other functions such as scheduling entries dynamically, reset any scheduled entries also at runtime, and adapted to work with internal time and timers functions of nodemcu (getting rid of the while loop).
My question is if it is ok to open another repository to host that code, and reference your repo as being the inspiration?
Thanks in advance!

**Comment by kedorlaomer** [comment]
No problem. I'm not using this anymore (I even forgot what this was meant for). If you need any help: I'm here.

There's no license yet; would you mind if I license under GPLv3?

**Comment by ezbella** [comment]
Ok thanks! Yes of course, i Will put the same license as you then.
Be well,

**Comment by kedorlaomer** [comment]
If there's anything else, I think it deserves a separate issue.

**Comment by ezbella** [comment]
Agree
